CREATE TABLE users (
    id CHAR(128) NOT NULL,
    name CHAR(100) NOT NULL,
    email CHAR(255) NOT NULL,
    password CHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    hits INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);